ban_message:
- "{PREFIX}"
- "&7You have been banned from the server" 
- "&7If you think it's an error, please contact a moderator or an administrator on discord:"
- "&6https://discord.gg/je4bcJW"
- "&7Reason:"
- "&6{REASON}"
- ""
- "&7Expiration time:"
- "&6{EXPIRATION}"

ban_reason:
- "none"
- "Cheat"
- "XRay"
- "Le marteau du ban a frappé !"
- "Asta la vista baby"

mute_reason:
- "Insultes"
- "Spam"

kick_reason:
- "AFK"
- "Comportement incorrect"