host: localhost
port: 3306
dbname: terminator
user: root
password:
# If true, use MySQL. If false, use MariaDB
mysql: true
ban_message:
- "{PREFIX}"
- "&7You have been banned from the server"
- "&7If you think it's an error, please contact a moderator or an administrator on discord:"
- "&6https://discord.gg/je4bcJW"
- "&7Reason:"
- "&6{REASON}"
- ""
- "&7Expiration time:"
- "&6{EXPIRATION}"
banip_message:
- "{PREFIX}"
- "&7Your ip have been banned from the server"
- "&7If you think it's an error, please contact a moderator or an administrator on discord:"
- "&6https://discord.gg/je4bcJW"
- "&7Reason:"
- "&6{REASON}"
- ""
- "&7Expiration time:"
- "&6{EXPIRATION}"