name: Terminator
main: me.oddlyoko.terminator.Terminator
version: 1.0.0
api-version: 1.13
authors: [0ddlyoko, Grandoz]
commands:
  ban:
    description: Ban a player
  unban:
    description: Unban a player
permissions:
  terminator.ban: 
    default: op
    description: Ban a player
  terminator.ban.see:
    default: op
    description: Show a message when a player is banned
  terminator.unban:
    default: op
    description: Unban a player that is already banned